In [1]:
# modified from https://github.com/pytorch/examples/blob/master/imagenet/main.py
import argparse
import os
import random
import shutil
import time
import warnings

import torch
import torch.nn as nn
import torch.nn.parallel
import torch.backends.cudnn as cudnn
import torch.distributed as dist
import torch.optim
import torch.multiprocessing as mp
import torch.utils.data
import torch.utils.data.distributed
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torch.nn.functional as F
from utils import *
import pandas as pd
import numpy as np
# from sklearn.utils import shuffle
from sklearn.preprocessing import StandardScaler
# from sklearn.preprocessing import MinMaxScaler
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, random_split


/home/usami/miniconda3/envs/human_action/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/usami/miniconda3/envs/human_action/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN3c107WarningC1ENS_7variantIJNS0_11UserWarningENS0_18DeprecationWarningEEEERKNS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(


In [2]:
#imports

# df_unsw_normal = pd.read_csv('/home/usami/Protocol-Based-Deep-Intrusion-Detection-for-DoS-Normal-and-DDoS-Attacks/normal_ddos_dos_classification/dataset/train/unsw_normal.csv')
df_bot_dos = pd.read_csv('/home/usami/Protocol-Based-Deep-Intrusion-Detection-for-DoS-Normal-and-DDoS-Attacks/normal_ddos_dos_classification/datasetv2/train/bot_iot_dos.csv')
df_bot_ddos = pd.read_csv('/home/usami/Protocol-Based-Deep-Intrusion-Detection-for-DoS-Normal-and-DDoS-Attacks/normal_ddos_dos_classification/datasetv2/train/bot_iot_ddos.csv')
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

/tmp/ipykernel_1286263/1538615253.py:4: DtypeWarning: Columns (7,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_bot_dos = pd.read_csv('/home/usami/Protocol-Based-Deep-Intrusion-Detection-for-DoS-Normal-and-DDoS-Attacks/normal_ddos_dos_classification/datasetv2/train/bot_iot_dos.csv')
/tmp/ipykernel_1286263/1538615253.py:5: DtypeWarning: Columns (7,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_bot_ddos = pd.read_csv('/home/usami/Protocol-Based-Deep-Intrusion-Detection-for-DoS-Normal-and-DDoS-Attacks/normal_ddos_dos_classification/datasetv2/train/bot_iot_ddos.csv')


In [3]:
df_combined = pd.concat([df_bot_dos, df_bot_ddos], ignore_index=True)
df_combined['sport'] = np.where(df_combined['sport'] == '0x0303', 0x0303, df_combined['sport'])
df_combined['sport'] = np.where(df_combined['sport'] == '0x5000', 0x5000, df_combined['sport'])
df_combined = df_combined[(df_combined['state']=='INT') | (df_combined['state']=='REQ')| (df_combined['state']=='RST')| (df_combined['state']=='ACC')| (df_combined['state']=='CON')| (df_combined['state']=='FIN')]
df_combined['flgs'] = df_combined['flgs'].map({'e': 0, 'e s': 1, 'e g': 2, 'eU': 3, 'e *':4, 'e d':5})
df_combined['state'] = df_combined['state'].map({'INT': 0, 'REQ': 1, 'RST': 2, 'ACC': 3, 'CON':4, 'FIN':6})

x = df_combined.loc[:, df_combined.columns != 'category']
x_ = np.zeros((x.shape[0], 49))
x_[:, :43] = x
x = x_

# x = (x-x.min())/(x.max()-x.min())

df_combined.category = pd.factorize(df_combined.category)[0]
y = df_combined['category']

scaler = StandardScaler()

x = scaler.fit_transform(x)

# for i in [0,1,2,3,7,8]:
#     x[:,i] = np.where(x[:,i] > 0, np.log(x[:,i]), 0)
x = x.reshape(x.shape[0], 1, 7, 7)   
# x = x[:1000,:,:,:] 
# y = y[:1000] 
x_label_data = torch.tensor(x, dtype=torch.float).to(device)
y_label_data = torch.tensor(y, dtype=torch.long).to(device)

dataset = TensorDataset(x_label_data, y_label_data)
train_size = int(0.7 * len(dataset))
valid_size = int(0.25 * len(dataset))
test_size = len(dataset) - train_size - valid_size
train_dataset, valid_dataset, test_dataset = random_split(dataset, [train_size, valid_size, test_size])

# Create data loaders
batch_size = 8192
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [4]:
quant = 'TNN'
class Netb(nn.Module):
    def __init__(self):
        super(Netb, self).__init__()
        # self.fc0 = QLinear(7 * 7, 64 * 64, bias=False)
        self.conv1 = QConv2d(in_channels=1, out_channels=64, kernel_size=3, padding=1, bias=False, quant=quant)
        self.conv2 = QConv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1, bias=False, quant=quant)
        self.linear1 = QLinear(128 * 7 * 7, 128, bias=False, quant=quant)
        self.linear2 = QLinear(128, 3, bias=False, quant=quant)
        self.act4 = nn.Softmax(dim = 1)
    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = x.view(x.size(0), -1)
        x = self.linear1(x)
        x = self.linear2(x)
        x = self.act4(x)
        return x
    
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_b = Netb().to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model_b.parameters(), 0.01,
                                momentum=0.9,
                                weight_decay=1e-4)
num_epochs = 2
for epoch in range(num_epochs):
    model_b.train()
    for i, (images, labels) in enumerate(train_loader):
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_b(images)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # model_ter1.set_weights_and_biases()

        if (i+1) % 10 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}', end='\r')
    
    model_b.eval()
    with torch.no_grad():
        correct = 0
        total = 0
        for images, labels in valid_loader:
            images = images.to(device)
            labels = labels.to(device)
            
            outputs = model_b(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        accuracy = 100 * correct / total
        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Accuracy: {accuracy:.2f}%')

# Final evaluation on the test set
model_b.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_b(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f'Test Accuracy: {test_accuracy:.2f}%')

torch.save(model_b.state_dict(), 'saved_best_model_bcnn.pt')

Epoch [1/2], Validation Accuracy: 50.01%9
Epoch [2/2], Validation Accuracy: 99.77%6
Test Accuracy: 99.77%


In [5]:
model_b.conv1.state_dict()

OrderedDict([('weight',
              tensor([[[[-3.1629e-01,  2.4065e-01,  6.1298e-01],
                        [ 2.7990e-01, -1.1899e-01, -2.8196e-01],
                        [-2.7077e-01,  3.2687e-01, -3.3006e-01]]],
              
              
                      [[[-2.6325e-01,  6.0372e-02,  1.8215e-01],
                        [ 3.2982e-01,  4.0291e-01, -1.6692e-01],
                        [-2.8385e-01,  5.3480e-01,  6.9567e-02]]],
              
              
                      [[[-2.7984e-01, -2.2804e-01,  3.2300e-01],
                        [-1.5694e-01,  1.1238e-01, -3.9037e-01],
                        [-1.9040e-01,  7.9845e-02, -2.7079e-01]]],
              
              
                      [[[ 2.2837e-01,  1.3461e-01,  1.4282e-01],
                        [ 3.2680e-01, -3.8740e-01, -1.4030e-01],
                        [-7.2367e-02,  2.1851e-01,  2.2384e-01]]],
              
              
                      [[[ 9.0394e-02,  3.1203e-01,  4.4128e-01],
   

In [24]:
model_b.conv1

QConv2d(
  1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
  (input_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
  (weight_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
)

In [50]:
(torch.fmod(model_b.conv1.state_dict()['weight']/model_b.conv1.weight_quantizer.state_dict()['running_delta']+1,2)-1).abs().pow(1)

tensor([[[[8.6106e-02, 2.7830e-01, 1.7809e-01],
          [2.4692e-01, 2.7913e-01, 1.0008e-01],
          [2.0015e-01, 3.2876e-01, 2.0271e-01]]],


        [[[2.8224e-01, 3.0148e-01, 2.8664e-01],
          [1.2415e-01, 1.3971e-01, 3.0236e-01],
          [1.5310e-01, 8.7484e-02, 3.9108e-02]]],


        [[[8.2710e-03, 2.2504e-01, 2.8798e-01],
          [1.2752e-01, 1.0479e-01, 2.2738e-01],
          [3.2659e-01, 2.7886e-01, 2.2951e-03]]],


        [[[2.7731e-01, 1.3200e-01, 2.6663e-02],
          [1.9780e-01, 2.7314e-01, 1.2136e-01],
          [2.7118e-01, 1.7272e-01, 1.8345e-01]]],


        [[[2.7523e-01, 4.2209e-02, 4.8123e-02],
          [3.2174e-01, 2.2556e-01, 3.0469e-01],
          [1.5142e-01, 1.9522e-01, 1.6372e-01]]],


        [[[2.4898e-01, 2.7724e-01, 3.0745e-01],
          [2.5904e-01, 1.3815e-01, 1.5676e-01],
          [1.0280e-01, 2.1560e-01, 1.7103e-01]]],


        [[[8.6907e-02, 1.0597e-02, 2.1674e-01],
          [3.1502e-01, 2.4978e-01, 4.2611e-02],
          [1.842

In [93]:
model_b.conv1.weight_quantizer

Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)

In [95]:
model_b.conv1.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.4353e+03,  2.7436e+03, -2.0409e+02],
                        [ 2.1623e+04, -4.3044e+03,  3.9876e+03],
                        [ 5.9744e+02, -1.2407e+04,  3.9065e+03]]],
              
              
                      [[[ 1.3254e+04, -1.6517e+04, -1.1340e+02],
                        [-7.7118e+04, -4.6868e+04, -5.9631e+04],
                        [-4.2603e+04,  6.9442e+02, -7.8251e+02]]],
              
              
                      [[[-1.3693e+05,  6.1051e+04, -1.5195e+04],
                        [ 4.6610e+03, -6.7291e+04, -1.0787e+04],
                        [ 3.7346e+03,  1.3347e+03, -4.1305e+04]]],
              
              
                      [[[ 2.6612e+02, -6.2397e+04, -1.2234e+04],
                        [-1.2794e+04, -9.7570e+04, -1.0762e+04],
                        [-1.1474e+04,  1.6172e+04,  1.1040e+02]]],
              
              
                      [[[-1.7083e+03,  3.7934e+03, -9.3908e+02],
   

In [91]:
def _ternary(x: torch.Tensor, delta: torch.Tensor):
    
    return (x >= delta.expand_as(x)).float() - (x <= -delta.expand_as(x)).float()

class _ternary_py(torch.autograd.Function):
    @staticmethod
    def ternary_backward(grad_output: torch.Tensor, x: torch.Tensor, delta: torch.Tensor, order: int, threshold: torch.Tensor):
        scale = 2 * delta
        # assert torch.prod((threshold <= scale).float())
        tmp = torch.zeros_like(grad_output)
        tmp += ((x >= -threshold.expand_as(x)) & (x <= threshold.expand_as(x))).float() * order * \
               (torch.fmod(x / delta.expand_as(x) + 3, 2) - 1).abs().pow(order - 1)
        return grad_output * x

    @staticmethod
    def forward(ctx, *inputs) -> torch.Tensor:
        input_f, running_delta, delta, momentum, training, ctx.order = inputs
        device = input_f.device

        if momentum > 0:
            if training:
                ctx.delta = torch.sum(torch.abs(input_f), dim=0) * (delta / input_f.shape[0])  # = delta * |input_f|_1 / n
                running_delta.data = momentum * ctx.delta.to(device) + (1.0 - momentum) * running_delta.data.to(device)
            else:
                ctx.delta = running_delta.data.to(device)
        else:
            ctx.delta = delta.to(device)
        # input_t = _ternary(input_f, ctx.delta) * (2 * ctx.delta)
        input_t = _ternary(input_f, ctx.delta)
        ctx.save_for_backward(input_f)
        return input_t

    @staticmethod
    def backward(ctx, *grad_outputs):
        grad_output, = grad_outputs
        input_f, = ctx.saved_tensors
        grad_input = _ternary_py.ternary_backward(grad_output, input_f, ctx.delta, ctx.order, 2. * ctx.delta)
        return grad_input, None, None, None, None, None, None, None, None, None


def ternary(input_f: torch.Tensor, running_delta : torch.Tensor, delta : torch.Tensor, momentum, training, order):
    return _ternary_py.apply(input_f, running_delta, delta, momentum, training, order)


class Ternary(torch.nn.Module):
    def __init__(self):
        super(Ternary, self).__init__()
        config = {}
        self.config = config
        self.delta = config.setdefault("delta", 0.5)
        # self.delta = torch.ones(1)/2
        self.first_time = 1
        self.momentum = config.setdefault("momentum", 0.01)
        self.track_running_stats = config.setdefault("track_running_stats", True)
        self.order = config.setdefault('order', 2)
        # self.use_scale = config.setdefault('use_scale', True)
        assert self.momentum <= 1 and self.order > 0 and self.delta > 0
        self.register_buffer("running_delta", torch.zeros(1))
        self.reset_parameters()

    def reset_parameters(self):
        if self.momentum > 0:
            self.running_delta.copy_(self.delta * 0.7979)
        else:
            self.running_delta.copy_(self.delta)

    def forward(self, input_f):
        if(self.first_time == 1):
            self.delta = torch.full(input_f.shape[1:], 0.5).to(input_f.device)
            self.register_buffer("running_delta", torch.ones(input_f.shape[1:]))
            self.first_time = 0
        return ternary(input_f, self.running_delta, self.delta, self.momentum,
                       self.training and self.track_running_stats, self.order)

    def extra_repr(self):
        return ", ".join(["{}={}".format(k, v) for k, v in self.config.items()])
    

class QConv2d(torch.nn.Conv2d):
    qa_config = {}
    qw_config = {}

    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=False,
                 padding_mode='zeros', quant = 'BNN'):
        super().__init__(in_channels, out_channels, kernel_size, stride, padding, dilation, groups, bias, padding_mode)
        
        if quant == 'BNN':
            self.input_quantizer = BinaryActivation()
            self.weight_quantizer = BinaryActivation()
        elif quant == 'TNN':
            self.input_quantizer = Ternary()
            self.weight_quantizer = Ternary()
        elif quant == 'TBN':
            self.input_quantizer = Ternary()
            self.weight_quantizer = BinaryActivation()    

    def forward(self, input_f):
        input_t = self.input_quantizer(input_f)
        weight_b = self.weight_quantizer(self.weight)
        out = F.conv2d(input_t, weight_b, self.bias, self.stride, self.padding, self.dilation, self.groups)
        return out

In [12]:
model_b.conv1.state_dict()

OrderedDict([('weight',
              tensor([[[[ 2.2831e+05,  2.0081e+06,  1.4261e+03],
                        [ 1.5268e+06,  4.7754e+05,  3.0952e+06],
                        [ 1.4880e+05,  1.2882e+06,  2.3670e+05]]],
              
              
                      [[[ 1.8460e+04, -1.1685e+04,  9.9244e+04],
                        [ 2.4314e+05,  1.6098e+05,  8.2070e+05],
                        [ 1.1873e+05,  1.9227e+06, -7.2484e+05]]],
              
              
                      [[[ 3.4784e+05, -1.2463e+04, -1.0733e+06],
                        [-7.4996e+05, -3.2268e+06, -1.6184e+06],
                        [-1.4101e+06, -1.0386e+06, -2.0152e+04]]],
              
              
                      [[[-3.5425e+05, -7.8562e+05, -7.9452e+05],
                        [-1.1709e+05,  3.5671e+05, -1.1520e+06],
                        [-4.8135e+06, -1.2061e+06, -6.5107e+04]]],
              
              
                      [[[ 3.4437e+04,  5.2433e+05, -1.4542e+04],
   

In [36]:
torch.randn(a.shape[1:])

torch.Size([32, 3, 32, 32])

In [32]:
original_tensor = torch.randn(5, 3, 32, 32)

# Tạo một tensor mới với chiều đầu tiên là 1 và các chiều còn lại giống với original_tensor
new_tensor = original_tensor.unsqueeze(0)

print("Kích thước của tensor gốc:", original_tensor.shape)
print("Kích thước của tensor mới:", new_tensor.shape)

Kích thước của tensor gốc: torch.Size([5, 3, 32, 32])
Kích thước của tensor mới: torch.Size([1, 5, 3, 32, 32])


In [39]:
a

tensor([[[[-1.3330e+00, -1.6434e-01,  1.7784e-01,  ...,  1.0874e+00,
            1.4750e-01,  1.8268e-02],
          [ 1.1886e+00, -4.6246e-01, -8.6303e-01,  ...,  8.7721e-02,
            1.7596e-04,  2.7147e+00],
          [ 1.3421e+00,  8.1970e-01,  1.8004e+00,  ..., -2.1520e+00,
           -1.0850e+00,  9.2588e-01],
          ...,
          [ 4.1000e-01,  1.7993e+00, -1.4350e-01,  ..., -2.8157e-01,
           -1.1568e+00, -4.3381e-01],
          [ 1.4590e+00, -1.6834e+00, -1.0979e+00,  ..., -1.7303e-01,
            2.3212e-01, -9.3571e-01],
          [-1.2582e+00,  3.0522e-03, -7.8769e-01,  ...,  5.0674e-02,
           -1.3585e+00,  1.3506e+00]],

         [[-9.1935e-02, -2.1071e-02, -1.6548e-01,  ..., -1.9203e-01,
            3.3605e-01,  5.6250e-01],
          [ 4.7130e-01, -9.3570e-01,  6.7361e-01,  ..., -6.6349e-01,
           -1.7495e-01,  6.6976e-01],
          [-1.1675e+00,  5.6528e-01, -7.2621e-01,  ...,  3.0877e-02,
            9.9779e-01, -1.2332e+00],
          ...,
     

In [38]:
a.numel()

98304

In [5]:
torch.rand(2, 3, 4, 5)

tensor([[[[6.6036e-01, 7.4628e-01, 8.0437e-01, 7.3732e-03, 1.6553e-01],
          [4.8740e-01, 6.9564e-01, 3.2979e-02, 1.3541e-02, 3.3923e-01],
          [1.4498e-01, 5.3208e-01, 3.5419e-01, 4.3338e-01, 5.1223e-01],
          [9.9440e-01, 4.2872e-01, 9.8546e-01, 3.4336e-01, 5.1852e-01]],

         [[2.9319e-01, 7.1360e-01, 7.6793e-01, 2.5023e-03, 9.2198e-01],
          [6.7495e-01, 3.5660e-01, 1.0229e-01, 1.3583e-01, 9.0678e-01],
          [9.6906e-01, 1.4432e-01, 1.2654e-01, 8.0159e-01, 2.3653e-02],
          [3.5362e-01, 2.6968e-01, 1.2114e-01, 6.0512e-01, 1.9963e-01]],

         [[3.8699e-01, 4.9097e-01, 9.8929e-01, 5.6672e-03, 8.9495e-01],
          [5.6219e-01, 8.4884e-01, 6.5803e-01, 5.1749e-01, 2.4113e-01],
          [9.3882e-01, 4.1945e-01, 5.6967e-01, 4.2127e-01, 3.7244e-01],
          [8.6861e-01, 5.6593e-01, 5.1845e-01, 2.2156e-01, 1.8890e-01]]],


        [[[6.8888e-01, 1.4864e-01, 9.2520e-01, 2.8272e-01, 4.9821e-01],
          [7.0582e-01, 6.2804e-01, 6.6619e-01, 4.4015e-0

In [ ]:
def _ternary(x: torch.Tensor, delta: float):
    return (x >= delta).float() - (x <= -delta).float()

class _ternary_py(torch.autograd.Function):
    @staticmethod
    def ternary_backward(grad_output: torch.Tensor, x: torch.Tensor, delta: float, order: int, threshold: torch.Tensor):
        scale = 2 * delta
        assert torch.prod((threshold <= scale).float())
        tmp = torch.zeros_like(grad_output)
        tmp += ((x >= -threshold) & (x <= threshold)).float() * order * \
               (torch.fmod(x / delta + 3, 2) - 1).abs().pow(order - 1)
        return grad_output * tmp

    @staticmethod
    def forward(ctx, *inputs) -> torch.Tensor:
        input_f, running_delta, delta, momentum, training, ctx.order = inputs
        device = input_f.device
        delta = delta.to(device)
        running_delta = running_delta.to(device)

        if momentum > 0:
            if training:
                ctx.delta = input_f.norm(1).item() * (delta / input_f.numel())  # = delta * |input_f|_1 / n
                running_delta.data = momentum * ctx.delta + (1.0 - momentum) * running_delta.data
            else:
                ctx.delta = running_delta.data.item()
        else:
            ctx.delta = delta.item()
        
        input_t = _ternary(input_f, ctx.delta)
        ctx.save_for_backward(input_f)
        return input_t

    @staticmethod
    def backward(ctx, *grad_outputs):
        grad_output, = grad_outputs
        input_f, = ctx.saved_tensors
        grad_input = _ternary_py.ternary_backward(grad_output, input_f, ctx.delta, ctx.order, 2. * ctx.delta)
        return grad_input, None, None, None, None, None, None, None, None, None

def ternary(input_f: torch.Tensor, running_delta: torch.Tensor, delta: torch.Tensor, momentum, training, order):
    return _ternary_py.apply(input_f, running_delta, delta, momentum, training, order)

class Ternary(torch.nn.Module):
    def __init__(self):
        super(Ternary, self).__init__()
        config = {}
        self.config = config
        self.delta = torch.tensor([0.5])
        self.momentum = config.setdefault("momentum", 0.01)
        self.track_running_stats = config.setdefault("track_running_stats", True)
        self.order = config.setdefault('order', 2)
        assert self.momentum <= 1 and self.order > 0 and self.delta > 0
        self.register_buffer("running_delta", torch.zeros(1))
        self.reset_parameters()

    def reset_parameters(self):
        if self.momentum > 0:
            self.running_delta.copy_(self.delta * 0.7979)
        else:
            self.running_delta.copy_(self.delta)

    def forward(self, input_f):
        if self.delta == torch.tensor([0.5]):
            self.delta = torch.full(input_f.shape, 0.5).to(input_f.device)
            self.register_buffer("running_delta", torch.zeros(input_f.shape).to(input_f.device))

        return ternary(input_f, self.running_delta, self.delta, self.momentum,
                       self.training and self.track_running_stats, self.order)

    def extra_repr(self):
        return ", ".join(["{}={}".format(k, v) for k, v in self.config.items()])

# Example usage:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Ternary().to(device)
input_tensor = torch.randn(10, 10).to(device)
output_tensor = model(input_tensor)
print(output_tensor)

tensor([[-1.,  1.,  0.,  0.,  1.,  1.,  1.,  1., -1.,  0.],
        [ 0., -1.,  1.,  0.,  1.,  1., -1., -1.,  1.,  1.],
        [ 1.,  0.,  1., -1.,  0.,  1.,  0.,  1.,  0., -1.],
        [-1.,  1., -1.,  0.,  1.,  1.,  0.,  1., -1., -1.],
        [ 0.,  1.,  0.,  1., -1.,  0.,  1.,  0.,  1.,  1.],
        [ 0.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.],
        [-1.,  0., -1.,  0., -1.,  1.,  0.,  0.,  1., -1.],
        [-1., -1., -1.,  0.,  1.,  0.,  1., -1.,  0., -1.],
        [ 0.,  1., -1., -1.,  1., -1.,  1.,  0.,  0., -1.],
        [-1.,  1., -1.,  1.,  0.,  1.,  0.,  0.,  1., -1.]], device='cuda:0')


In [ ]:
a = torch.tensor([[1, -2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]]).float()

In [13]:
delta = torch.tensor([[1, -2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]]).float()

In [14]:
a.norm(1).item() * (delta / a.numel())

tensor([[  5.0000, -10.0000,  15.0000],
        [ 20.0000,  25.0000,  30.0000],
        [ 35.0000,  40.0000,  45.0000]])

In [17]:
running_delta

tensor([0.3183])

In [27]:
delta == torch.tensor([0.5])

tensor([True])

In [19]:
delta.shape[0]==1

True

In [31]:
a = torch.tensor([[1, -2, 3], 
                  [4, 5, 6],
                  [7, 8, 9]])

b = torch.tensor([[9, 8, 7], 
                  [6, 5, 4],
                  [3, 2, 1]])

# So sánh từng giá trị và lưu vào ma trận c
# Nếu giá trị tại (i, j) của a lớn hơn giá trị tại (i, j) của b, gán giá trị 1 cho c[i, j]
# Ngược lại, gán giá trị 0 cho c[i, j]
(a <= b).float()

tensor([[1., 1., 1.],
        [1., 1., 0.],
        [0., 0., 0.]])

In [32]:
a.float().norm(1)

tensor(45.)

In [13]:
for i in range(len(torch.rand(2, 3).shape)):
    for j in 

2

In [9]:
torch.full([64, 1, 3, 3], 0.5)

tensor([[[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000]]],


        [[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000]]],


        [[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000]]],


        [[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000]]],


        [[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000]]],


        [[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000]]],


        [[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000]]],


        [[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000]]],


        [[[0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.5000],
          [0.5000, 0.5000, 0.500

In [151]:
def _ternary(x: torch.Tensor, delta: float):
    return (x >= delta).float() - (x <= -delta).float()
def _binary(x: torch.Tensor):
    return (x >= 0).float() - (x < 0).float()

def save_model_parameters_to_txt(model, file_path):
    input_thres = []
    weight_thres = []
    quant_type = []
    i_q = '0'
    w_q = '0'
    for name, module in model.named_modules():        
        if 'input_quantizer' in name:
            if 'Binary' in str(module):
                input_thres = np.append(input_thres,0.0)
                i_q = 'B'
            else:
                input_thres = np.append(input_thres, module.running_delta.item())
                i_q = 'T'
        elif 'weight_quantizer' in name:
            if 'Binary' in str(module):
                weight_thres = np.append(weight_thres, 0.0)
                w_q = 'B'
            else:
                weight_thres = np.append(weight_thres, module.running_delta.item())
                w_q = 'T'
        if i_q != '0' and w_q != '0':
            if i_q == 'B' and w_q == 'B':
                quant_type = np.append(quant_type,'BNN')
            elif i_q == 'T' and w_q == 'B':
                quant_type = np.append(quant_type,'TBN')
            elif i_q == 'T' and w_q == 'T':
                quant_type = np.append(quant_type,'TNN')
            i_q = '0'
            w_q = '0'
    cnt=0
    with open(file_path, 'w') as f:
        for name, param in model.named_parameters():
            layer_name = name.split('.')[0]
            if 'conv' in name:
                f.write(f'{name}\n')
                f.write(f'layer_name: {layer_name}\n')
                f.write(f'input_channel: {param.shape[1]}\n')
                f.write(f'output_channel: {param.shape[0]}\n')
                f.write(f'kernel_size: 3\n')
                f.write(f'stride: 1\n')
                f.write(f'padding: 1\n')
                f.write(f'dilation: 1\n')
                if(quant_type[cnt] == 'BNN'):
                    f.write(f'quant_type: 0\n')
                    quant_write = 1
                elif(quant_type[cnt] == 'TBN'):
                    f.write(f'quant_type: 1\n')
                    quant_write = 1
                elif(quant_type[cnt] == 'TNN'):
                    f.write(f'quant_type: 2\n')
                    quant_write = 2
                f.write(f'input_thres: {input_thres[cnt]}\n')
                namen = name.split('.')[0]
                # param = getattr(getattr(model, namen).weight_quantizer, 'forward')(param)
                param = _ternary(param, weight_thres[cnt])
                for param_e in param:
                    # param_e = getattr(getattr(model, namen).weight_quantizer, 'forward')(param_e)
                    # param_e = _ternary(param_e, weight_thres[cnt])
                    param_padding = torch.zeros(32*int(np.ceil(param_e.shape[0]/32)), param_e.shape[1],param_e.shape[2])
                    param_padding[0:param_e.shape[0],:,:] = param_e
                    param_e = param_padding
                    sichannel = int(np.ceil(param_e.shape[0]/32))
                    for c in range(sichannel):
                        for q in range(quant_write):
                            for i in range(param_e.shape[1]):
                                for j in range(param_e.shape[2]):
                                    if(quant_type[cnt] == 'BNN' or quant_type[cnt] == 'TBN'):
                                        hex_conv = convert_and_concatenate(_binary(param_e[(c+1)*32-32:(c+1)*32, i, j]))
                                        if j == param_e.shape[2]-1:
                                            f.write(f'0x{hex_conv}')
                                        else:
                                            f.write(f'0x{hex_conv}, ')
                                    elif(quant_type[cnt] == 'TNN'):
                                        hex_conv_bit0, hex_conv_bit1 = convert_and_concatenate_tnn(param_e[(c+1)*32-32:(c+1)*32, i, j])
                                        if(q == 0):
                                            if j == param_e.shape[2]-1:
                                                f.write(f'0x{hex_conv_bit0}')
                                            else:
                                                f.write(f'0x{hex_conv_bit0}, ')
                                        elif(q == 1):
                                            if j == param_e.shape[2]-1:
                                                f.write(f'0x{hex_conv_bit1}')
                                            else:
                                                f.write(f'0x{hex_conv_bit1}, ')
                                f.write(f'\n')
                        f.write(f'\n')

            elif 'fc' in name or 'linear' in name:
                f.write(f'{name}\n')
                f.write(f'layer_name: {layer_name}\n')
                f.write(f'input_channel: {param.shape[1]}\n')
                f.write(f'output_channel: {param.shape[0]}\n')
                if(quant_type[cnt] == 'BNN'):
                    f.write(f'quant_type: 0\n')
                elif(quant_type[cnt] == 'TBN'):
                    f.write(f'quant_type: 1\n')
                elif(quant_type[cnt] == 'TNN'):
                    f.write(f'quant_type: 2\n')
                f.write(f'input_thres: {input_thres[cnt]}\n')

                if(quant_type[cnt] == 'BNN' or quant_type[cnt] == 'TBN'):
                    param = _binary(param)
                    for param_e in param:
                        hex_conv = convert_and_concatenate(param_e)
                        segments = [hex_conv[i:i+8] for i in range(0, len(hex_conv), 8)]
                        segments.reverse()
                        for segment in segments:
                            f.write(f'0x{segment}\n')
                    f.write(f'\n')
                elif(quant_type[cnt] == 'TNN'):
                    # param = getattr(getattr(model, namen).weight_quantizer, 'forward')(param)
                    param = _ternary(param, weight_thres[cnt])
                    # print(name)
                    for param_e in param:
                        hex_conv_bit0, hex_conv_bit1 = convert_and_concatenate_tnn(param_e)
                        segments0 = [hex_conv_bit0[i:i+8] for i in range(0, len(hex_conv_bit0), 8)]
                        segments1 = [hex_conv_bit1[i:i+8] for i in range(0, len(hex_conv_bit1), 8)]
                        segments0.reverse()
                        segments1.reverse()
                        for j in range (len(segments0)):
                            f.write(f'0x{segments0[j]}\n')
                            f.write(f'0x{segments1[j]}\n')
                    f.write(f'\n')
            cnt+=1        
        return 0



quant = 'TNN'
class Netb(nn.Module):
    def __init__(self):
        super(Netb, self).__init__()
        # self.fc0 = QLinear(7 * 7, 64 * 64, bias=False)
        self.conv1 = QConv2d(in_channels=1, out_channels=64, kernel_size=3, padding=1, bias=False, quant=quant)
        self.conv2 = QConv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1, bias=False, quant=quant)
        self.linear1 = QLinear(128 * 7 * 7, 128, bias=False, quant=quant)
        self.linear2 = QLinear(128, 3, bias=False, quant=quant)
        self.act4 = nn.Softmax(dim = 1)
    def forward(self, x):
        x = self.conv1(x)
        x1 = self.conv2(x)
        x = x1.view(x1.size(0), -1)
        x = self.linear1(x)
        x = self.linear2(x)
        
        x = self.act4(x)
        return x1
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_b = Netb().to(device)
model_b.load_state_dict(torch.load('saved_best_model_bcnn.pt'))
model_b.eval()
save_model_parameters_to_txt(model_b, 'tcnn_model_parameters.txt')


0

In [11]:
for name, param in model_b.named_parameters():
    if 'conv1' in name:
        for param_e in param:
            namen = name.split('.')[0]
            param_raw = param_e
            param_e = getattr(getattr(model_b, namen).weight_quantizer, 'forward')(param_e)
            param_padding = torch.zeros(32*int(np.ceil(param_e.shape[0]/32)), param_e.shape[1],param_e.shape[2])
            param_padding[0:param_e.shape[0],:,:] = param_e
            param_e = param_padding
            sichannel = int(np.ceil(param_e.shape[0]/32))
            for c in range(sichannel):
                for q in range(2):
                    for i in range(param_e.shape[1]):
                        for j in range(param_e.shape[2]):
                            hex_conv_bit0, hex_conv_bit1 = convert_and_concatenate_tnn(param_padding[(c+1)*32-32:(c+1)*32-1, i, j])
                            print(param_raw[0, i, j])
                            if(q == 0):
                                if j == param_e.shape[2]-1:
                                    print(f'0x{hex_conv_bit0}')
                                else:
                                    print(f'0x{hex_conv_bit0}, ')
                            elif(q == 1):
                                if j == param_e.shape[2]-1:
                                    print(f'0x{hex_conv_bit1}')
                                else:
                                    print(f'0x{hex_conv_bit1}, ')
                    print(f'\n')
            print(f'\n')
            break
        break


tensor(0.2238, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000000, 
tensor(0.2295, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000000, 
tensor(0.2729, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000000
tensor(-0.0010, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000000, 
tensor(-0.2689, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000001, 
tensor(-0.2575, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000001
tensor(0.1577, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000000, 
tensor(0.1437, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000000, 
tensor(0.6278, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000000


tensor(0.2238, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000001, 
tensor(0.2295, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000001, 
tensor(0.2729, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000001
tensor(-0.0010, device='cuda:0', grad_fn=<SelectBackward0>)
0x00000000, 
tensor(-0.2689, device='cuda:0', grad_fn=<SelectBackward0>)
0x0000

In [101]:
class Ternary(torch.nn.Module):
    def __init__(self):
        super(Ternary, self).__init__()
        config = {}
        self.config = config
        self.delta = config.setdefault("delta", 0.5)
        self.momentum = config.setdefault("momentum", 0.01)
        self.track_running_stats = config.setdefault("track_running_stats", True)
        self.order = config.setdefault('order', 2)
        # self.use_scale = config.setdefault('use_scale', True)
        assert self.momentum <= 1 and self.order > 0 and self.delta > 0
        self.register_buffer("running_delta", torch.zeros(1))
        self.reset_parameters()

    def reset_parameters(self):
        if self.momentum > 0:
            self.running_delta.fill_(self.delta * 0.7979)
        else:
            self.running_delta.fill_(self.delta)

    def forward(self, input_f):
        return ternary(input_f, self.running_delta, self.delta, self.momentum,
                       self.training and self.track_running_stats, self.order)

    def extra_repr(self):
        return ", ".join(["{}={}".format(k, v) for k, v in self.config.items()])

class QConv2d(torch.nn.Conv2d):
    qa_config = {}
    qw_config = {}
    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=False,
                 padding_mode='zeros', quant = 'BNN'):
        super().__init__(in_channels, out_channels, kernel_size, stride, padding, dilation, groups, bias, padding_mode)
        
        if quant == 'BNN':
            self.input_quantizer = BinaryActivation()
            self.weight_quantizer = BinaryActivation()
        elif quant == 'TNN':
            self.input_quantizer = Ternary()
            self.weight_quantizer = Ternary()
        elif quant == 'TBN':
            self.input_quantizer = Ternary()
            self.weight_quantizer = BinaryActivation()
        self.i = 0

    def forward(self, input_f):
        input_t = self.input_quantizer(input_f)
        weight_b = self.weight_quantizer(self.weight)
        out = F.conv2d(input_t, weight_b, self.bias, self.stride, self.padding, self.dilation, self.groups)
        if(self.i == 0):
            self.i = 1
            # print(input_t)
            print(self.weight)
            print(weight_b)

        return out

In [161]:
def _ternary(x: torch.Tensor, delta: float):
    return (x >= delta).float() - (x <= -delta).float()

class _ternary_py(torch.autograd.Function):
    @staticmethod
    def ternary_backward(grad_output: torch.Tensor, x: torch.Tensor, delta: float, order: int, threshold: float):
        scale = 2 * delta
        assert threshold <= scale
        tmp = torch.zeros_like(grad_output)
        tmp += ((x >= -threshold) & (x <= threshold)).float() * order * \
               (torch.fmod(x / delta + 3, 2) - 1).abs().pow(order - 1)
        return grad_output * tmp

    @staticmethod
    def forward(ctx, *inputs) -> torch.Tensor:
        input_f, running_delta, delta, momentum, training, ctx.order = inputs
        if momentum > 0:
            if training:
                ctx.delta = input_f.norm(1).item() * (delta / input_f.numel())  # = delta * |input_f|_1 / n
                running_delta.data = momentum * ctx.delta + (1.0 - momentum) * running_delta.data
            else:
                ctx.delta = running_delta.data.item()
        else:
            ctx.delta = delta
        # input_t = _ternary(input_f, ctx.delta) * (2 * ctx.delta)
        input_t = _ternary(input_f, ctx.delta)
        ctx.save_for_backward(input_f)
        return input_t

    @staticmethod
    def backward(ctx, *grad_outputs):
        grad_output, = grad_outputs
        input_f, = ctx.saved_tensors
        grad_input = _ternary_py.ternary_backward(grad_output, input_f, ctx.delta, ctx.order, 2. * ctx.delta)
        return grad_input, None, None, None, None, None, None, None, None, None


def ternary(input_f: torch.Tensor, running_delta, delta, momentum, training, order):
    return _ternary_py.apply(input_f, running_delta, delta, momentum, training, order)


class Ternary(torch.nn.Module):
    def __init__(self):
        super(Ternary, self).__init__()
        config = {}
        self.config = config
        self.delta = config.setdefault("delta", 0.5)
        self.momentum = config.setdefault("momentum", 0.01)
        self.track_running_stats = config.setdefault("track_running_stats", True)
        self.order = config.setdefault('order', 2)
        # self.use_scale = config.setdefault('use_scale', True)
        assert self.momentum <= 1 and self.order > 0 and self.delta > 0
        self.register_buffer("running_delta", torch.zeros(1))
        self.reset_parameters()

    def reset_parameters(self):
        if self.momentum > 0:
            self.running_delta.fill_(self.delta * 0.7979)
        else:
            self.running_delta.fill_(self.delta)

    def forward(self, input_f):
        return ternary(input_f, self.running_delta, self.delta, self.momentum,
                       self.training and self.track_running_stats, self.order)

    def extra_repr(self):
        return ", ".join(["{}={}".format(k, v) for k, v in self.config.items()])

class QConv2d(torch.nn.Conv2d):
    qa_config = {}
    qw_config = {}

    def __init__(self, in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=False,
                 padding_mode='zeros', quant = 'BNN'):
        super().__init__(in_channels, out_channels, kernel_size, stride, padding, dilation, groups, bias, padding_mode)
        
        if quant == 'BNN':
            self.input_quantizer = BinaryActivation()
            self.weight_quantizer = BinaryActivation()
        elif quant == 'TNN':
            self.input_quantizer = Ternary()
            self.weight_quantizer = Ternary()
        elif quant == 'TBN':
            self.input_quantizer = Ternary()
            self.weight_quantizer = BinaryActivation()    

    def forward(self, input_f):
        input_t = self.input_quantizer(input_f)
        weight_b = self.weight_quantizer(self.weight)
        out = F.conv2d(input_t, weight_b, self.bias, self.stride, self.padding, self.dilation, self.groups)
        return out
    
class QLinear(torch.nn.Linear):
    qa_config = {}
    qw_config = {}
    def __init__(self, in_features, out_features, bias=False, quant = 'BNN'):
        super().__init__(in_features, out_features, bias)
        if quant == 'BNN':
            self.input_quantizer = BinaryActivation()
            self.weight_quantizer = BinaryActivation()
        elif quant == 'TNN':
            self.input_quantizer = Ternary()
            self.weight_quantizer = Ternary()
        elif quant == 'TBN':
            self.input_quantizer = Ternary()
            self.weight_quantizer = BinaryActivation()    
    def forward(self, input_f):
        input_b = self.input_quantizer(input_f)
        weight_b = self.weight_quantizer(self.weight)
        out = F.linear(input_b, weight_b, self.bias)
        return out
quant = 'TNN'
class Netb(nn.Module):
    def __init__(self):
        super(Netb, self).__init__()
        # self.fc0 = QLinear(7 * 7, 64 * 64, bias=False)
        self.conv1 = QConv2d(in_channels=1, out_channels=64, kernel_size=3, padding=1, bias=False, quant=quant)
        self.conv2 = QConv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1, bias=False, quant=quant)
        self.linear1 = QLinear(128 * 7 * 7, 128, bias=False, quant=quant)
        self.linear2 = QLinear(128, 3, bias=False, quant=quant)
        self.act4 = nn.Softmax(dim = 1)
    def forward(self, x):
        x = self.conv1(x)
        x1 = self.conv2(x)
        x = x1.view(x1.size(0), -1)
        x = self.linear1(x)
        x = self.linear2(x)
        print(x)
        x = self.act4(x)
        return x1
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_b = Netb().to(device)
model_b.load_state_dict(torch.load('saved_best_model_tcnn_128.pt'))
model_b.eval()

Netb(
  (conv1): QConv2d(
    1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
    (input_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
    (weight_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
  )
  (conv2): QConv2d(
    64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
    (input_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
    (weight_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
  )
  (linear1): QLinear(
    in_features=6272, out_features=128, bias=False
    (input_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
    (weight_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
  )
  (linear2): QLinear(
    in_features=128, out_features=3, bias=False
    (input_quantizer): Ternary(delta=0.5, momentum=0.01, track_running_stats=True, order=2)
    

In [27]:
model_b.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_b(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f'Test Accuracy: {test_accuracy:.2f}%')

tensor([[[[ 27.,  27.,  18.,  ...,   3., -10., -18.],
          [-22., -21., -42.,  ...,  -2.,  30.,   6.],
          [ -1.,  -9., -25.,  ..., -10.,   6.,   5.],
          ...,
          [  7., -34.,  -6.,  ..., -28.,  -2.,  -4.],
          [  3.,   7.,  -6.,  ...,   0.,  11.,  12.],
          [-14., -12.,  17.,  ...,  -7.,  23.,  20.]],

         [[ -5., -29., -29.,  ...,   8.,  28.,  15.],
          [  9.,   2.,  14.,  ...,   7.,  -8., -19.],
          [  6.,   3.,  20.,  ...,   1.,  -5.,   3.],
          ...,
          [ 18.,   1.,  39.,  ...,  28.,  15.,   5.],
          [ -8.,  -2.,   7.,  ...,  20.,   4.,  -9.],
          [-16.,   6.,   7.,  ..., -12.,   1., -16.]],

         [[-17., -11.,  -4.,  ..., -14.,  15.,  -3.],
          [ 18.,  31.,  26.,  ...,   4.,   8.,   7.],
          [  2.,  13.,  12.,  ..., -12.,  -5.,  22.],
          ...,
          [ 20.,  -9.,  11.,  ...,   6.,  26.,   0.],
          [-21.,  -3.,  -3.,  ...,  -3.,  19.,   0.],
          [-11., -19.,   6.,  ...

In [162]:
image = torch.tensor([[[[ 1., -1.,  1., -1.,  1., -1.,  1.],
                        [ 1., -1.,  1., -1.,  1., -1.,  1.],
                        [ 1., -1.,  1., -1.,  1., -1.,  1.],
                        [ 1., -1.,  1., -1.,  1., -1.,  1.],
                        [ 1., -1.,  1., -1.,  1., -1.,  1.],
                        [ 1., -1.,  1., -1.,  1., -1.,  1.],
                        [ 1., -1.,  1., -1.,  1., -1.,  1.]]]], device='cuda:0')
a = model_b(image)

tensor([[-27.,  13.,   3.]], device='cuda:0', grad_fn=<MmBackward0>)


In [185]:
import torch
import torch.nn.functional as F

# Định nghĩa trọng số của kernel với giá trị cụ thể
weight = torch.tensor([[[[1.0, 2.0, 3.0],
                         [4.0, 5.0, 6.0],
                         [7.0, 8.0, 9.0]]]])

# Tạo một tensor đầu vào cụ thể
input_tensor = torch.tensor([[[[1.0, 2.0, 3.0, 4.0],
                               [5.0, 6.0, 7.0, 8.0],
                               [9.0, 10.0, 11.0, 12.0],
                               [13.0, 14.0, 15.0, 16.0]]]])

# Thực hiện transpose convolution với stride=1, padding=1
output_tensor = F.conv_transpose2d(input_tensor, weight, stride=3, padding=1)

print("Input tensor:")
print(input_tensor)
print("Kernel weights:")
print(weight)
print("Output tensor:")
print(output_tensor)

Input tensor:
tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])
Kernel weights:
tensor([[[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]])
Output tensor:
tensor([[[[ 5.,  6.,  8., 10., 12., 12., 15., 18., 16., 20.],
          [ 8.,  9., 14., 16., 18., 21., 24., 27., 28., 32.],
          [10., 15.,  6., 12., 18.,  7., 14., 21.,  8., 16.],
          [25., 30., 24., 30., 36., 28., 35., 42., 32., 40.],
          [40., 45., 42., 48., 54., 49., 56., 63., 56., 64.],
          [18., 27., 10., 20., 30., 11., 22., 33., 12., 24.],
          [45., 54., 40., 50., 60., 44., 55., 66., 48., 60.],
          [72., 81., 70., 80., 90., 77., 88., 99., 84., 96.],
          [26., 39., 14., 28., 42., 15., 30., 45., 16., 32.],
          [65., 78., 56., 70., 84., 60., 75., 90., 64., 80.]]]])


In [229]:
def convert_and_concatenate(arr):
    # Chuyển đổi -1 thành 1 và 1 thành 0
    arr = torch.flip(arr, dims=[0])
    converted_arr = [1 if x == -1 else 0 for x in arr]
    # Ghép các phần tử lại thành một chuỗi
    concatenated_str = ''.join(map(str, converted_arr))

    current_length = len(concatenated_str)
    total_length = (np.ceil(current_length/32)*32).astype(int)
    if current_length < total_length:
        padding_length = int(total_length - current_length)
        concatenated_str = '0' * padding_length + concatenated_str
    # Chuyển chuỗi thành số nhị phân và sau đó thành số hex
    hex_value = hex(int(concatenated_str, 2))[2:]  # Bỏ tiền tố '0x'

    # Đảm bảo chuỗi hex đủ độ dài cần thiết
    hex_length = total_length // 4  # 1 hex digit = 4 bits
    if len(hex_value) < hex_length:
        hex_value = '0' * (hex_length - len(hex_value)) + hex_value
    return hex_value

def to_hex(x):
    return f"0x{x:08x}"

def save_model_parameters_to_txt(model, file_path):
    with open(file_path, 'w') as f:
        for name, param in model.named_parameters():
            layer_name = name.split('.')[0]
            if 'conv' in name:
                f.write(f'{name}\n')
                f.write(f'layer_name: {layer_name}\n')
                f.write(f'input_channel: {param.shape[1]}\n')
                f.write(f'output_channel: {param.shape[0]}\n')
                f.write(f'kernel_size: 3\n')
                f.write(f'stride: 1\n')
                f.write(f'padding: 1\n')
                f.write(f'dilation: 1\n')
                f.write(f'quant_type: 0\n')
                f.write(f'input_thres: 0\n')
                for param_e in param:
                    sichannel = int(np.ceil(param_e.shape[0]/32))
                    # param_q = torch.zeros([sichannel,param_e.shape[1],param_e.shape[2]])
                    # param_q = param_q.int()
                    for c in range(sichannel):
                        for i in range(param_e.shape[1]):
                            for j in range(param_e.shape[2]):
                                hex_conv = convert_and_concatenate(_binary(param_e[sichannel*0:sichannel*32, i, j]))
                                if j == param_e.shape[2]-1:
                                    f.write(f'0x{hex_conv}')
                                else:
                                    f.write(f'0x{hex_conv}, ')
                            f.write(f'\n')
                        f.write(f'\n')
            if 'fc' in name or 'linear' in name:
                f.write(f'{name}\n')
                f.write(f'layer_name: {layer_name}\n')
                f.write(f'input_channel: {param.shape[1]}\n')
                f.write(f'output_channel: {param.shape[0]}\n')
                f.write(f'quant_type: 0\n')
                f.write(f'input_thres: 0.0\n')
                param = _binary(param)
                for param_e in param:
                    hex_conv = convert_and_concatenate(param_e)
                    segments = [hex_conv[i:i+8] for i in range(0, len(hex_conv), 8)]
                    segments.reverse()
                    for segment in segments:
                        f.write(f'0x{segment}\n')
                f.write(f'\n')
        return 0

# Gọi hàm để lưu thông số mô hình
a = save_model_parameters_to_txt(model_b, 'bcnn_model_parameters.txt')

In [105]:
i = 0
for name, param in model_b.named_parameters():
    if 'conv' in name:
        for param_e in param:
            sichannel = int(np.ceil(param_e.shape[0]/32))
            param_q = torch.zeros([sichannel,param_e.shape[1],param_e.shape[2]])
            for c in range(sichannel):
                for i in range(param_e.shape[1]):
                    for j in range(param_e.shape[2]):
                        param_q[c,i,j] = int(convert_and_concatenate(_binary(param_e[sichannel*0:sichannel*32, i, j])),16)
            param_q = param_q.int()
            # for i in param_q:
            #     print(i)
            # print(hex(param_q))
            # print(f"Giá trị hex: {hex(param_q)}")
            # print(hex(param_q))
        print(param.shape)
        # break

torch.Size([32, 1, 3, 3])
torch.Size([64, 32, 3, 3])


# **BNN**

In [338]:
class BinaryActivationFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        # Binarize input to -1 or 1
        output = input.sign()
        output[output==0] = 1
        ctx.save_for_backward(input)
        return output

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input.abs() > 1] = 0
        return grad_input

class BinaryActivation(nn.Module):
    def forward(self, input):
        return BinaryActivationFunction.apply(input)

class QLinear(torch.nn.Linear):
    qa_config = {}
    qw_config = {}

    def __init__(self, in_features, out_features, bias=False):
        super().__init__(in_features, out_features, bias)
        # self.input_quantizer = BinaryActivation()
        self.weight_quantizer = BinaryActivation()

    def forward(self, input_f):
        # input_t = self.input_quantizer(input_f)
        weight_b = self.weight_quantizer(self.weight)
        out = F.linear(input_f, weight_b, self.bias)
        return out

In [339]:
class Netb(nn.Module):
    def __init__(self):
        super(Netb, self).__init__()
        self.input_quantizer = BinaryActivation()

        self.linear1 = QLinear(13, 128, bias = False)
        self.bn1 = nn.BatchNorm1d(128)
        # self.i1 = nn.Identity()

        self.linear2 = QLinear(128, 128, bias = False)
        self.bn2 = nn.BatchNorm1d(128)
        # self.i2 = nn.Identity()

        self.linear3 = QLinear(128, 128, bias = False)
        self.bn3 = nn.BatchNorm1d(128)
        # self.i3 = nn.Identity()

        self.linear4 = QLinear(128, 3, bias = False)
        self.act4 = nn.Softmax(dim = 1)

    def forward(self, x):
        x = self.input_quantizer(x)
        x = self.linear1(x)

        x = self.input_quantizer(x)
        x = self.linear2(x)
        # x = self.bn2(x)
        # x = self.i2(x)
        x = self.input_quantizer(x)
        x = self.linear3(x)
        # x = self.bn3(x)
        # x = self.i3(x)
        x = self.input_quantizer(x)
        x = self.linear4(x)
        x = self.act4(x)
        return x
    
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_b = Netb().to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model_b.parameters(), 0.01,
                                momentum=0.9,
                                weight_decay=1e-4)
num_epochs = 5
for epoch in range(num_epochs):
    model_b.train()
    for i, (images, labels) in enumerate(train_loader):
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_b(images)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # model_ter1.set_weights_and_biases()

        if (i+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}', end='\r')
    
    model_b.eval()
    with torch.no_grad():
        correct = 0
        total = 0
        for images, labels in valid_loader:
            images = images.to(device)
            labels = labels.to(device)
            
            outputs = model_b(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        accuracy = 100 * correct / total
        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Accuracy: {accuracy:.2f}%')

# Final evaluation on the test set
model_b.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_b(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f'Test Accuracy: {test_accuracy:.2f}%')

torch.save(model_b.state_dict(), 'saved_best_model_bnn.pt')

Epoch [1/5], Validation Accuracy: 91.39%6
Epoch [2/5], Validation Accuracy: 89.58%6
Epoch [3/5], Validation Accuracy: 92.36%8
Epoch [4/5], Validation Accuracy: 92.36%5
Epoch [5/5], Validation Accuracy: 92.36%4
Test Accuracy: 92.25%


In [729]:
class BinaryActivationFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        # Binarize input to -1 or 1
        output = input.sign()
        output[output==0] = 1
        ctx.save_for_backward(input)
        return output

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input.abs() > 1] = 0
        return grad_input

class BinaryActivation(nn.Module):
    def forward(self, input):
        return BinaryActivationFunction.apply(input)

class QLinear(torch.nn.Linear):
    qa_config = {}
    qw_config = {}
    def __init__(self, in_features, out_features, bias=True):
        super().__init__(in_features, out_features, bias)
        self.weight_quantizer = BinaryActivation()
    def forward(self, input_f):
        # weight_b = self.weight_quantizer(self.weight)
        out = F.linear(input_f, self.weight, self.bias)
        return out

class Netb(nn.Module):
    def __init__(self):
        super(Netb, self).__init__()
        self.input_quantizer = BinaryActivation()
        self.linear1 = QLinear(13, 128, bias = False)

        self.linear2 = QLinear(128, 128, bias = False)

        self.linear3 = QLinear(128, 128, bias = False)

        self.linear4 = QLinear(128, 3, bias = False)
        self.act4 = nn.Softmax(dim = 1)

    def forward(self, x):
        x = self.input_quantizer(x)
        x = self.linear1(x)
        print("linear1")
        print(x)

        x = self.input_quantizer(x)
        x = self.linear2(x)
        print("linear2")
        print(x)

        x = self.input_quantizer(x)
        x = self.linear3(x)
        print("linear3")
        print(x)
        
        x = self.input_quantizer(x)
        x = self.linear4(x)
        print("linear4")
        print(x)
        x = self.act4(x)
        print(x)
        return x

model_bnn = Netb().to(device)
model_bnn.linear1.state_dict()['weight'].copy_(model_b.linear1.state_dict()['weight'].sign())
model_bnn.linear2.state_dict()['weight'].copy_(model_b.linear2.state_dict()['weight'].sign())
model_bnn.linear3.state_dict()['weight'].copy_(model_b.linear3.state_dict()['weight'].sign())
model_bnn.linear4.state_dict()['weight'].copy_(model_b.linear4.state_dict()['weight'].sign())

tensor([[ 1., -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1., -1., -1.,
          1.,  1., -1.,  1., -1.,  1., -1.,  1., -1., -1.,  1., -1., -1.,  1.,
         -1.,  1., -1., -1., -1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1.,
         -1.,  1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1.,
         -1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1., -1., -1.,  1.,
         -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,
         -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1., -1.,  1.,  1.,  1.,
          1., -1., -1., -1.,  1., -1., -1., -1.,  1.,  1., -1., -1.,  1.,  1.,
         -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1., -1.,  1., -1., -1.,
          1., -1.],
        [-1.,  1., -1.,  1., -1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,
         -1., -1., -1.,  1., -1., -1., -1., -1., -1.,  1., -1.,  1.,  1.,  1.,
         -1., -1., -1.,  1., -1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,
         -1.,  1.,  1.,  1.,  1.

In [730]:
model_bnn.eval()
correct = 0
total = 0
# images = torch.tensor([[0.0000,  0.0000,  0.0000,  0.0000, -0.6556,  0.9844,  0.2236, -1.4968, -1.4968, -0.9711, -0.1279,  0.2186,  0.2208]]).to(device)
images = torch.tensor([[ 0.,          0.,          0.,          0.,         -0.48889792, -1.0158767,
  0.2236068,  -1.4960896,  -1.4960909,   0.74484456, -0.1279424,   0.21856718,
  0.22078077]]).to(device)
with torch.no_grad():
    outputs = model_bnn(images)


linear1
tensor([[  5.,   7.,   7.,   1.,  -3.,  -3.,  -7.,   3.,  -1.,  -7.,  -3.,   3.,
          -5.,   1.,   1.,   5.,  -5.,   1.,  -7.,   5.,   1.,   1.,  -1.,   1.,
          -3.,   5.,  -3.,   3.,   1.,   5.,  -3.,   3.,   1.,  -3.,   5.,  -3.,
          -3.,  -1.,   9.,  -1.,  -5.,   3.,   1.,   3.,   9.,   3.,   5.,  -7.,
          -1.,   5.,   5.,  -3.,   3.,   5.,  -3.,   7.,  -3.,   5.,   3.,  -7.,
           5.,  -1.,  -5.,  -3.,  -3.,   3.,  -7.,  -3.,  -3.,  -3.,   1.,   5.,
           3.,   1.,  -1.,   1.,  -3.,  -1.,   3.,   1.,   1.,   3.,   1.,  -1.,
           7.,  -3.,  -5.,  -5.,  -7.,  -3.,  -5.,  -1.,  -3.,  -5.,   1.,  -9.,
          -3.,  -5.,   5.,  -3., -11.,   7.,  -1.,   3.,  -5.,   3.,  -3.,  -1.,
           5.,  -5.,  -3.,  -7.,  -1.,  -5.,   5.,   1.,  -1.,   3.,  -7.,   5.,
           3.,  -5.,  -5.,   5.,   7.,  -5.,  -3.,  -5.]], device='cuda:0')
linear2
tensor([[-24., -16., -14., -32., -32.,  20.,  -4., -16., -10.,  -8.,  10., -26.,
         -22., -1

In [341]:
model_bnn.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_bnn(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f'Test Accuracy: {test_accuracy:.2f}%')
# torch.save(model_bnn.state_dict(), 'saved_best_model_bnn_1.pt')

Test Accuracy: 92.25%


In [272]:
def convert_and_concatenate(arr):
    # Chuyển đổi -1 thành 1 và 1 thành 0
    arr = torch.flip(arr, dims=[0])
    converted_arr = [1 if x == -1 else 0 for x in arr]
    # Ghép các phần tử lại thành một chuỗi
    concatenated_str = ''.join(map(str, converted_arr))

    current_length = len(concatenated_str)
    total_length = (np.ceil(current_length/32)*32).astype(int)
    if current_length < total_length:
        padding_length = int(total_length - current_length)
        concatenated_str = '0' * padding_length + concatenated_str
    # Chuyển chuỗi thành số nhị phân và sau đó thành số hex
    hex_value = hex(int(concatenated_str, 2))[2:]  # Bỏ tiền tố '0x'

    # Đảm bảo chuỗi hex đủ độ dài cần thiết
    hex_length = total_length // 4  # 1 hex digit = 4 bits
    if len(hex_value) < hex_length:
        hex_value = '0' * (hex_length - len(hex_value)) + hex_value
    return hex_value

def save_model_parameters_to_txt(model, file_path):
    with open(file_path, 'w') as f:
        for name, param in model.named_parameters():
            f.write(f'{name}\n')
            f.write(f'input_channel: {param.shape[1]}\n')
            f.write(f'output_channel: {param.shape[0]}\n')
            for param_e in param:
                hex_conv = convert_and_concatenate(param_e)
                segments = [hex_conv[i:i+8] for i in range(0, len(hex_conv), 8)]
                segments.reverse()
                for segment in segments:
                    f.write(f'0x{segment}\n')
            f.write(f'\n')
    return 0

# Gọi hàm để lưu thông số mô hình
a = save_model_parameters_to_txt(model_bnn, 'bnn_model_parameters.txt')

# **FP**

In [302]:
class Net_fp(nn.Module):
    def __init__(self):
        super(Net_fp, self).__init__()
        self.linear1 = nn.Linear(13, 128, bias = False)
        # self.bn1 = nn.BatchNorm1d(128)
        self.act1 = nn.ReLU()

        self.linear2 = nn.Linear(128, 128, bias = False)
        # self.bn2 = nn.BatchNorm1d(128)
        self.act2 = nn.ReLU()


        self.linear3 = nn.Linear(128, 128, bias = False)
        # self.bn3 = nn.BatchNorm1d(128)
        self.act3 = nn.ReLU()

        self.linear4 = nn.Linear(128, 3, bias = False)
        self.act4 = nn.Softmax(dim = 1)

    def forward(self, x):

        x = self.linear1(x)
        # x = self.bn1(x)
        x = self.act1(x)

        x = self.linear2(x)
        # x = self.bn2(x)
        x = self.act2(x)

        x = self.linear3(x)
        # x = self.bn3(x)
        x = self.act3(x)

        x = self.linear4(x)
        x = self.act4(x)
        return x
    
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_fp = Net_fp().to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model_fp.parameters(), 0.01,
                                momentum=0.9,
                                weight_decay=1e-4)
num_epochs = 2
for epoch in range(num_epochs):
    model_fp.train()
    for i, (images, labels) in enumerate(train_loader):
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_fp(images)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # model_ter1.set_weights_and_biases()

        if (i+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}', end='\r')
    
    model_fp.eval()
    with torch.no_grad():
        correct = 0
        total = 0
        for images, labels in valid_loader:
            images = images.to(device)
            labels = labels.to(device)
            
            outputs = model_fp(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        accuracy = 100 * correct / total
        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Accuracy: {accuracy:.2f}%')

# Final evaluation on the test set
model_fp.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_fp(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f'Test Accuracy: {test_accuracy:.2f}%')

torch.save(model_fp.state_dict(), 'saved_best_model_fp.pt')

Epoch [1/2], Validation Accuracy: 91.52%1
Epoch [2/2], Validation Accuracy: 91.63%0
Test Accuracy: 91.51%


In [303]:
def save_model_fp_parameters_to_txt(model, file_path):
    with open(file_path, 'w') as f:
        for name, param in model.named_parameters():
            f.write(f'{name}\n')
            if('linear' in name and 'weight'in name):
                f.write(f'input_channel: {param.shape[1]}\n')
                f.write(f'output_channel: {param.shape[0]}\n')
            f.write(f'{param}\n')
            f.write(f'\n')
    return 0

# Gọi hàm để lưu thông số mô hình
a = save_model_fp_parameters_to_txt(model_fp, 'fp_model_parameters.txt')

# **TNN**

In [623]:
def _ternary(x: torch.Tensor, delta: float):
    return (x >= delta).float() - (x <= -delta).float()

class _ternary_py(torch.autograd.Function):
    @staticmethod
    def ternary_backward(grad_output: torch.Tensor, x: torch.Tensor, delta: float, order: int, threshold: float):
        scale = 2 * delta
        assert threshold <= scale
        tmp = torch.zeros_like(grad_output)
        tmp += ((x >= -threshold) & (x <= threshold)).float() * order * \
               (torch.fmod(x / delta + 3, 2) - 1).abs().pow(order - 1)
        return grad_output * tmp

    @staticmethod
    def forward(ctx, *inputs) -> torch.Tensor:
        input_f, running_delta, delta, momentum, training, ctx.order = inputs
        if momentum > 0:
            if training:
                ctx.delta = input_f.norm(1).item() * (delta / input_f.numel())  # = delta * |input_f|_1 / n
                running_delta.data = momentum * ctx.delta + (1.0 - momentum) * running_delta.data
            else:
                ctx.delta = running_delta.data.item()
        else:
            ctx.delta = delta
        # input_t = _ternary(input_f, ctx.delta) * (2 * ctx.delta)
        input_t = _ternary(input_f, ctx.delta)
        ctx.save_for_backward(input_f)
        return input_t

    @staticmethod
    def backward(ctx, *grad_outputs):
        grad_output, = grad_outputs
        input_f, = ctx.saved_tensors
        grad_input = _ternary_py.ternary_backward(grad_output, input_f, ctx.delta, ctx.order, 2. * ctx.delta)
        return grad_input, None, None, None, None, None, None, None, None, None


def ternary(input_f: torch.Tensor, running_delta, delta, momentum, training, order):
    return _ternary_py.apply(input_f, running_delta, delta, momentum, training, order)


class Ternary(torch.nn.Module):
    def __init__(self):
        super(Ternary, self).__init__()
        config = {}
        self.config = config
        self.delta = config.setdefault("delta", 0.5)
        self.momentum = config.setdefault("momentum", 0.01)
        self.track_running_stats = config.setdefault("track_running_stats", True)
        self.order = config.setdefault('order', 2)
        # self.use_scale = config.setdefault('use_scale', True)
        assert self.momentum <= 1 and self.order > 0 and self.delta > 0
        self.register_buffer("running_delta", torch.zeros(1))
        self.reset_parameters()

    def reset_parameters(self):
        if self.momentum > 0:
            self.running_delta.fill_(self.delta * 0.7979)
        else:
            self.running_delta.fill_(self.delta)

    def forward(self, input_f):
        return ternary(input_f, self.running_delta, self.delta, self.momentum,
                       self.training and self.track_running_stats, self.order)

    def extra_repr(self):
        return ", ".join(["{}={}".format(k, v) for k, v in self.config.items()])
class QLinear(torch.nn.Linear):
    def __init__(self, in_features, out_features, bias=False):
        super().__init__(in_features, out_features, bias)
        self.input_quantizer = Ternary()
        self.weight_quantizer = Ternary()

    def forward(self, input_f):
        input_t = self.input_quantizer(input_f)
        weight_b = self.weight_quantizer(self.weight)
        out = F.linear(input_t, weight_b, self.bias)
        return out

In [422]:
class Net_tnn(nn.Module):
    def __init__(self):
        super(Net_tnn, self).__init__()

        self.linear1 = QLinear(13, 128, bias = False)
        # self.bn1 = nn.BatchNorm1d(128)
        # self.i1 = nn.Identity()

        self.linear2 = QLinear(128, 128, bias = False)
        # self.bn2 = nn.BatchNorm1d(128)
        # self.i2 = nn.Identity()

        self.linear3 = QLinear(128, 128, bias = False)
        # self.bn3 = nn.BatchNorm1d(128)
        # self.i3 = nn.Identity()

        self.linear4 = QLinear(128, 3, bias = False)
        self.act4 = nn.Softmax(dim = 1)

    def forward(self, x):
        # x = self.input_quantizer(x)
        x = self.linear1(x)
        # x = self.bn1(x)

        # x = self.input_quantizer(x)
        x = self.linear2(x)
        # x = self.bn2(x)

        # x = self.input_quantizer(x)
        x = self.linear3(x)
        # x = self.bn3(x)

        # x = self.input_quantizer(x)
        x = self.linear4(x)
        x = self.act4(x)
        return x
    
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_tnn = Net_tnn().to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model_tnn.parameters(), 0.01,
                                momentum=0.9,
                                weight_decay=1e-4)
num_epochs = 4
for epoch in range(num_epochs):
    model_tnn.train()
    for i, (images, labels) in enumerate(train_loader):
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_tnn(images)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # model_ter1.set_weights_and_biases()

        if (i+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}', end='\r')
    
    model_tnn.eval()
    with torch.no_grad():
        correct = 0
        total = 0
        for images, labels in valid_loader:
            images = images.to(device)
            labels = labels.to(device)
            
            outputs = model_tnn(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        accuracy = 100 * correct / total
        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Accuracy: {accuracy:.2f}%')

# Final evaluation on the test set
model_tnn.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_tnn(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f'Test Accuracy: {test_accuracy:.2f}%')

torch.save(model_tnn.state_dict(), 'saved_best_model_tnn.pt')

Epoch [1/4], Validation Accuracy: 84.68%2
Epoch [2/4], Validation Accuracy: 91.85%8
Epoch [3/4], Validation Accuracy: 91.85%4
Epoch [4/4], Validation Accuracy: 91.85%9
Test Accuracy: 91.74%


In [655]:
def convert_and_concatenate_tnn(arr):
    arr = torch.flip(arr, dims=[0])
    # Chuyển đổi -1 thành 1 và 1 thành 0
    converted_bit0_arr = [1 if x == -1 else 0 for x in arr]
    converted_bit1_arr = [1 if x == 1 else 0 for x in arr]
    concatenated_bit0_str = ''.join(map(str, converted_bit0_arr))
    concatenated_bit1_str = ''.join(map(str, converted_bit1_arr))


    current_length = np.max([len(concatenated_bit0_str),len(concatenated_bit0_str)])
    total_length = (np.ceil(current_length/32)*32).astype(int)
    if current_length < total_length:
        padding_length0 = int(total_length - len(concatenated_bit0_str))
        padding_length1 = int(total_length - len(concatenated_bit1_str))
        concatenated_bit0_str = '0' * padding_length0 + concatenated_bit0_str
        concatenated_bit1_str = '0' * padding_length1 + concatenated_bit1_str

    # Chuyển chuỗi thành số nhị phân và sau đó thành số hex
    hex_value_bit0 = hex(int(concatenated_bit0_str, 2))[2:]  # Bỏ tiền tố '0x'
    hex_value_bit1 = hex(int(concatenated_bit1_str, 2))[2:]  # Bỏ tiền tố '0x'
    # Đảm bảo chuỗi hex đủ độ dài cần thiết
    if(len(hex_value_bit0)>len(hex_value_bit1)):
        hex_value_bit1 = '0' * (len(hex_value_bit0)-len(hex_value_bit1)) + hex_value_bit1
    elif(len(hex_value_bit0)<len(hex_value_bit1)):
        hex_value_bit0 = '0' * (len(hex_value_bit1)-len(hex_value_bit0)) + hex_value_bit0

    hex_length = total_length // 4  # 1 hex digit = 4 bits
    if len(hex_value_bit0) < hex_length:
        hex_value_bit0 = '0' * (hex_length - len(hex_value_bit0)) + hex_value_bit0
        hex_value_bit1 = '0' * (hex_length - len(hex_value_bit1)) + hex_value_bit1
    return hex_value_bit0, hex_value_bit1

def save_tnn_model_parameters_to_txt(model, file_path):
    input_thres = []
    weight_thres = []
    for name, module in model.named_modules():        
        if 'input_quantizer' in name:
            input_thres = np.append(input_thres, module.running_delta.item())
        if 'weight_quantizer' in name:
            weight_thres = np.append(weight_thres, module.running_delta.item())
    # input_thres = np.append(input_thres, 0)
    cnt=0
    with open(file_path, 'w') as f:
        for name, param in model.named_parameters():
            f.write(f'{name}\n')
            f.write(f'input_channel: {param.shape[1]}\n')
            f.write(f'output_channel: {param.shape[0]}\n')
            f.write(f'input_thres: {input_thres[cnt]}\n')

            param = _ternary(param, weight_thres[cnt])
            print(name)
            for param_e in param:
                hex_conv_bit0, hex_conv_bit1 = convert_and_concatenate_tnn(param_e)
                segments0 = [hex_conv_bit0[i:i+8] for i in range(0, len(hex_conv_bit0), 8)]
                segments1 = [hex_conv_bit1[i:i+8] for i in range(0, len(hex_conv_bit1), 8)]
                segments0.reverse()
                segments1.reverse()
                for j in range (len(segments0)):
                    f.write(f'0x{segments0[j]}\n')
                    f.write(f'0x{segments1[j]}\n')
            f.write(f'\n')
            cnt+=1
    return 0

# Gọi hàm để lưu thông số mô hình
a = save_tnn_model_parameters_to_txt(model_tnn, 'tnn_model_parameters.txt')

linear1.weight
linear2.weight
linear3.weight
linear4.weight


In [649]:
class Net_tnn(nn.Module):
    def __init__(self):
        super(Net_tnn, self).__init__()

        self.linear1 = QLinear(13, 128, bias = False)
        # self.bn1 = nn.BatchNorm1d(128)
        # self.i1 = nn.Identity()

        self.linear2 = QLinear(128, 128, bias = False)
        # self.bn2 = nn.BatchNorm1d(128)
        # self.i2 = nn.Identity()

        self.linear3 = QLinear(128, 128, bias = False)
        # self.bn3 = nn.BatchNorm1d(128)
        # self.i3 = nn.Identity()

        self.linear4 = QLinear(128, 3, bias = False)
        self.act4 = nn.Softmax(dim = 1)

    def forward(self, x):
        # x = self.input_quantizer(x)
        x = self.linear1(x)
        print("linear1: ")
        print(x)

        # x = self.input_quantizer(x)
        x = self.linear2(x)
        print("linear2: ")
        print(x)
        # x = self.bn2(x)

        # x = self.input_quantizer(x)
        x = self.linear3(x)
        print("linear3: ")
        print(x)
        # x = self.bn3(x)

        # x = self.input_quantizer(x)
        x = self.linear4(x)
        print("linear4: ")
        print(x)
        x = self.act4(x)
        return x
    
model_tnn_test = Net_tnn().to(device)
checkpoint = torch.load('saved_best_model_tnn.pt')
model_tnn_test.load_state_dict(checkpoint)

<All keys matched successfully>

In [650]:
# Final evaluation on the test set
model_tnn_test.eval()
correct = 0
total = 0
test = torch.tensor([[0.0000,  0.0000,  0.0000,  0.0000, -0.6556,  0.9844,  0.2236, -1.4968, -1.4968, -0.9711, -0.1279,  0.2186,  0.2208]]).to(device)
with torch.no_grad():
    outputs = model_tnn_test(test)

# test_accuracy = 100 * correct / total
# print(f'Test Accuracy: {test_accuracy:.2f}%')

linear1: 
tensor([[-3.,  0.,  3.,  2., -4.,  0.,  1.,  1.,  0.,  1., -3., -1.,  0.,  1.,
          1.,  1., -3.,  1.,  1.,  1.,  3.,  0., -3.,  1.,  1., -1., -1.,  0.,
          0., -1., -1.,  1., -1.,  5., -2.,  1., -3., -2.,  1.,  1., -1.,  4.,
          1., -2., -1., -2.,  1.,  2.,  1., -2.,  1.,  0.,  0.,  1.,  1., -1.,
          0.,  2.,  0., -1.,  2.,  2.,  0., -1., -2., -3., -3., -3., -3.,  1.,
         -4.,  1., -3., -2., -1.,  1.,  0.,  3., -1.,  1.,  2.,  0., -2., -3.,
          0.,  2., -1.,  1., -2., -2.,  2.,  2., -1., -2.,  1.,  0.,  2.,  4.,
          5., -3., -2., -1.,  1., -1., -4.,  0.,  2., -2.,  1., -1.,  0., -1.,
          0.,  1.,  3.,  1.,  1.,  3.,  3., -1.,  1.,  2.,  3., -2.,  0.,  2.,
          0., -2.]], device='cuda:0')
linear2: 
tensor([[ 12.,   6., -10., -14.,  -5.,   8.,  10.,   1.,  31.,  12.,  10.,  -5.,
          -2.,  11., -12., -24.,  -1.,  -2.,  11.,  -4.,  12.,   4.,   2., -14.,
          -5.,  -2.,  -3.,   1.,   7., -15.,   5.,  -4.,  -4.,   9., 

0.3157

# **TBN**

In [ ]:
class QLinear(torch.nn.Linear):
    def __init__(self, in_features, out_features, bias=False):
        super().__init__(in_features, out_features, bias)
        self.input_quantizer = Ternary()
        self.weight_quantizer = BinaryActivation()

    def forward(self, input_f):
        input_t = self.input_quantizer(input_f)
        weight_b = self.weight_quantizer(self.weight)
        out = F.linear(input_t, weight_b, self.bias)
        return out

In [675]:
class Net_tbn(nn.Module):
    def __init__(self):
        super(Net_tbn, self).__init__()

        self.linear1 = QLinear(13, 128, bias = False)
        # self.bn1 = nn.BatchNorm1d(128)
        # self.i1 = nn.Identity()

        self.linear2 = QLinear(128, 128, bias = False)
        # self.bn2 = nn.BatchNorm1d(128)
        # self.i2 = nn.Identity()

        self.linear3 = QLinear(128, 128, bias = False)
        # self.bn3 = nn.BatchNorm1d(128)
        # self.i3 = nn.Identity()

        self.linear4 = QLinear(128, 3, bias = False)
        self.act4 = nn.Softmax(dim = 1)

    def forward(self, x):
        # x = self.input_quantizer(x)
        x = self.linear1(x)
        # x = self.bn1(x)

        # x = self.input_quantizer(x)
        x = self.linear2(x)
        # x = self.bn2(x)

        # x = self.input_quantizer(x)
        x = self.linear3(x)
        # x = self.bn3(x)

        # x = self.input_quantizer(x)
        x = self.linear4(x)
        x = self.act4(x)
        return x
    
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_tbn = Net_tbn().to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model_tbn.parameters(), 0.01,
                                momentum=0.9,
                                weight_decay=1e-4)
num_epochs = 4
for epoch in range(num_epochs):
    model_tbn.train()
    for i, (images, labels) in enumerate(train_loader):
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_tbn(images)
        loss = criterion(outputs, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        # model_ter1.set_weights_and_biases()

        if (i+1) % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}', end='\r')
    
    model_tbn.eval()
    with torch.no_grad():
        correct = 0
        total = 0
        for images, labels in valid_loader:
            images = images.to(device)
            labels = labels.to(device)
            
            outputs = model_tbn(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        accuracy = 100 * correct / total
        print(f'Epoch [{epoch + 1}/{num_epochs}], Validation Accuracy: {accuracy:.2f}%')

# Final evaluation on the test set
model_tbn.eval()
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        
        outputs = model_tbn(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

test_accuracy = 100 * correct / total
print(f'Test Accuracy: {test_accuracy:.2f}%')

torch.save(model_tbn.state_dict(), 'saved_best_model_tbn.pt')

Epoch [1/4], Validation Accuracy: 86.25%1
Epoch [2/4], Validation Accuracy: 88.99%8
Epoch [3/4], Validation Accuracy: 92.04%7
Epoch [4/4], Validation Accuracy: 92.04%3
Test Accuracy: 91.98%


In [682]:
def _binary(x: torch.Tensor):
    return (x >= 0).float() - (x < 0).float()

def convert_and_concatenate_tbn(arr):
    # Chuyển đổi -1 thành 1 và 1 thành 0
    arr = torch.flip(arr, dims=[0])
    converted_arr = [1 if x == -1 else 0 for x in arr]
    # Ghép các phần tử lại thành một chuỗi
    concatenated_str = ''.join(map(str, converted_arr))

    current_length = len(concatenated_str)
    total_length = (np.ceil(current_length/32)*32).astype(int)
    if current_length < total_length:
        padding_length = int(total_length - current_length)
        concatenated_str = '0' * padding_length + concatenated_str
    # Chuyển chuỗi thành số nhị phân và sau đó thành số hex
    hex_value = hex(int(concatenated_str, 2))[2:]  # Bỏ tiền tố '0x'

    # Đảm bảo chuỗi hex đủ độ dài cần thiết
    hex_length = total_length // 4  # 1 hex digit = 4 bits
    if len(hex_value) < hex_length:
        hex_value = '0' * (hex_length - len(hex_value)) + hex_value
    return hex_value

def save_tbn_model_parameters_to_txt(model, file_path):
    input_thres = []
    for name, module in model.named_modules():        
        if 'input_quantizer' in name:
            input_thres = np.append(input_thres, module.running_delta.item())
    # input_thres = np.append(input_thres, 0)
    cnt=0
    with open(file_path, 'w') as f:
        for name, param in model.named_parameters():
            f.write(f'{name}\n')
            f.write(f'input_channel: {param.shape[1]}\n')
            f.write(f'output_channel: {param.shape[0]}\n')
            f.write(f'input_thres: {input_thres[cnt]}\n')

            param = _binary(param)
            print(name)
            for param_e in param:
                hex_conv_bit = convert_and_concatenate_tbn(param_e)
                segments = [hex_conv_bit[i:i+8] for i in range(0, len(hex_conv_bit), 8)]
                segments.reverse()
                for j in range (len(segments)):
                    f.write(f'0x{segments[j]}\n')
            f.write(f'\n')
            cnt+=1
    return 0

# Gọi hàm để lưu thông số mô hình
a = save_tbn_model_parameters_to_txt(model_tbn, 'tbn_model_parameters.txt')

linear1.weight
linear2.weight
linear3.weight
linear4.weight


In [684]:
class QLinear(torch.nn.Linear):
    def __init__(self, in_features, out_features, bias=False):
        super().__init__(in_features, out_features, bias)
        self.input_quantizer = Ternary()
        self.weight_quantizer = BinaryActivation()

    def forward(self, input_f):
        input_t = self.input_quantizer(input_f)
        weight_b = self.weight_quantizer(self.weight)
        out = F.linear(input_t, weight_b, self.bias)
        return out

class Net_tbn_test(nn.Module):
    def __init__(self):
        super(Net_tbn_test, self).__init__()

        self.linear1 = QLinear(13, 128, bias = False)
        # self.bn1 = nn.BatchNorm1d(128)
        # self.i1 = nn.Identity()

        self.linear2 = QLinear(128, 128, bias = False)
        # self.bn2 = nn.BatchNorm1d(128)
        # self.i2 = nn.Identity()

        self.linear3 = QLinear(128, 128, bias = False)
        # self.bn3 = nn.BatchNorm1d(128)
        # self.i3 = nn.Identity()

        self.linear4 = QLinear(128, 3, bias = False)
        self.act4 = nn.Softmax(dim = 1)

    def forward(self, x):
        # x = self.input_quantizer(x)
        x = self.linear1(x)
        print("linear1: ")
        print(x)

        # x = self.input_quantizer(x)
        x = self.linear2(x)
        print("linear2: ")
        print(x)
        # x = self.bn2(x)

        # x = self.input_quantizer(x)
        x = self.linear3(x)
        print("linear3: ")
        print(x)
        # x = self.bn3(x)

        # x = self.input_quantizer(x)
        x = self.linear4(x)
        print("linear4: ")
        print(x)
        x = self.act4(x)
        return x
    
model_tbn_test = Net_tbn_test().to(device)
checkpoint = torch.load('saved_best_model_tbn.pt')
model_tbn_test.load_state_dict(checkpoint)
model_tbn_test.linear1.state_dict()['weight'].copy_(_binary(model_tbn_test.linear1.state_dict()['weight']))
model_tbn_test.linear2.state_dict()['weight'].copy_(_binary(model_tbn_test.linear2.state_dict()['weight']))
model_tbn_test.linear3.state_dict()['weight'].copy_(_binary(model_tbn_test.linear3.state_dict()['weight']))
model_tbn_test.linear4.state_dict()['weight'].copy_(_binary(model_tbn_test.linear4.state_dict()['weight']))

tensor([[ 1., -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1.,
          1., -1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1., -1.,  1.,
         -1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,
          1.,  1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1., -1.,
          1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,  1., -1.,  1., -1.,
          1.,  1.,  1.,  1., -1., -1.,  1., -1., -1., -1.,  1.,  1., -1.,  1.,
         -1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
          1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
         -1., -1., -1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,  1.,  1.,
         -1., -1.],
        [-1.,  1., -1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,
          1.,  1., -1., -1.,  1.,  1., -1., -1., -1., -1., -1.,  1., -1.,  1.,
          1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1., -1.,
         -1.,  1., -1., -1.,  1.

In [686]:
# Final evaluation on the test set
model_tbn_test.eval()
correct = 0
total = 0
test = torch.tensor([[0.0000,  0.0000,  0.0000,  0.0000, -0.6556,  0.9844,  0.2236, -1.4968, -1.4968, -0.9711, -0.1279,  0.2186,  0.2208]]).to(device)
with torch.no_grad():
    outputs = model_tbn_test(test)

# test_accuracy = 100 * correct / total
# print(f'Test Accuracy: {test_accuracy:.2f}%')

linear1: 
tensor([[-1., -3.,  1., -1.,  3., -1., -3.,  3.,  3.,  1.,  1., -3.,  3., -3.,
          3.,  1.,  1.,  3.,  3., -1., -1., -1., -1.,  1., -3.,  1.,  1.,  1.,
          1.,  1.,  1., -1.,  3.,  5., -5., -1.,  3.,  1., -1., -1.,  5., -5.,
          1., -5.,  1., -3., -1., -3.,  5.,  1., -1., -1., -1.,  1., -3., -5.,
          1., -3., -3., -1.,  5., -3., -5.,  1., -1.,  3., -1., -1., -3.,  3.,
         -1.,  5., -1., -1., -5., -1., -3.,  1.,  5., -1.,  5.,  3.,  3., -1.,
          1.,  3., -1., -3.,  1.,  5.,  5.,  1.,  3.,  3.,  1.,  3.,  1.,  3.,
         -1., -1.,  1., -3.,  3., -5., -1.,  1., -3., -1.,  1.,  1.,  5.,  1.,
         -3.,  5.,  3., -1., -5., -1., -3., -1.,  5.,  3., -1., -1.,  1.,  1.,
         -3.,  1.]], device='cuda:0')
linear2: 
tensor([[ -4., -28., -30.,  -2.,   4.,  48.,  -2., -14.,  -4., -16.,   8.,  16.,
           6.,   4.,   8.,  28.,  -8., -16.,   6.,  -6.,  20.,  26.,   4., -30.,
          20., -10., -16.,   6.,   4., -42.,  18., -34., -10., -12., 

# **GENERATE TESTCASE**

In [752]:
df_combined = pd.concat([df_bot_dos, df_bot_ddos], ignore_index=True)

x = df_combined.loc[:, df_combined.columns != 'category']
# x = (x-x.min())/(x.max()-x.min())

df_combined.category = pd.factorize(df_combined.category)[0]
y = df_combined['category']

scaler = StandardScaler()
x = scaler.fit_transform(x)
for i in [0,1,2,3,7,8]:
    x[:,i] = np.where(x[:,i] > 0, np.log(x[:,i]), 0)
    
x_label_data = torch.tensor(x, dtype=torch.float).to(device)
y_label_data = torch.tensor(y, dtype=torch.long).to(device)

dataset = TensorDataset(x_label_data, y_label_data)
train_size = int(0.7 * len(dataset))
valid_size = int(0.275 * len(dataset))
test_size = len(dataset) - train_size - valid_size
train_dataset, valid_dataset, test_dataset = random_split(dataset, [train_size, valid_size, test_size])

# Create data loaders
batch_size = 8192
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

/tmp/ipykernel_12712/3797725696.py:12: RuntimeWarning: invalid value encountered in log
  x[:,i] = np.where(x[:,i] > 0, np.log(x[:,i]), 0)


In [753]:
test_size

84000

In [ ]:
def save_tbn_model_parameters_to_txt(model, file_path):
    input_thres = []
    for name, module in model.named_modules():        
        if 'input_quantizer' in name:
            input_thres = np.append(input_thres, module.running_delta.item())
    # input_thres = np.append(input_thres, 0)
    cnt=0
    with open(file_path, 'w') as f:
        for name, param in model.named_parameters():
            f.write(f'{name}\n')
            f.write(f'input_channel: {param.shape[1]}\n')
            f.write(f'output_channel: {param.shape[0]}\n')
            f.write(f'input_thres: {input_thres[cnt]}\n')

            param = _binary(param)
            print(name)
            for param_e in param:
                hex_conv_bit = convert_and_concatenate_tbn(param_e)
                segments = [hex_conv_bit[i:i+8] for i in range(0, len(hex_conv_bit), 8)]
                segments.reverse()
                for j in range (len(segments)):
                    f.write(f'0x{segments[j]}\n')
            f.write(f'\n')
            cnt+=1
    return 0

In [754]:

tc = 0


In [ ]:
file_path = 'testcase.txt'
with open(file_path, 'w') as f:
    for images, labels in test_loader:
        f.write(f'testcase: {tc}\n')
        f.write(f'data: {images[0]}\n'.replace(" ", ""))
        f.write(f'label: {labels[0].cpu().numpy()}\n')
        f.write(f'\n')
        tc +=1
